server:
  port: 8071

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ccccye123/spring-cloud-config-repo.git
          username: w0.0.3@163.com
          password: Totoro140704