server:
  port: 8070

spring:
  application:
    name: microservice-gateway-zuul

zuul:
#  ignored-services: microservice-consumer-movie
  routes:
    microservice-consumer-movie: /movie/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@discovery:8761/eureka/,http://user:password123@discovery:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: routes