server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/,http://user:password123@localhost:8762/eureka/

spring:
  application:
    name: service-ribbon