server:
  port: 8092

spring:
  application:
    name: microservice-consumer-movie

logging:
  level:
    org.ccccye.movie.feign.TestFeign: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule