server:
  port: 8092

spring:
  application:
    name: microservice-consumer-movie

logging:
  level:
    org.ccccye.movie.feign.TestFeign: DEBUG

feign:
  hystrix:
    enabled: true
# 说明：请务必注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
# 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
# 而，Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。
# 原文链接：https://blog.csdn.net/qyj19920704/article/details/80725981

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@discovery:8761/eureka/,http://user:password123@discovery:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule